from pathlib import Path
p=Path('/mnt/data/tg160303')

# treeBranches: apply per-branch overrides and taper
f=p/'src/components/world/treeBranches.js'
s=f.read_text()
old='''    branches.push({\n      index: branchIndex,\n      trunkT,\n      origin,\n      end,\n      direction,\n      length: branchLength,\n      thickness: structuralThickness,\n      localRadius,\n      azimuth,\n      elevation: branchElevation,\n    });'''
new='''    const overrides = branchDefinition?.overrides?.[branchIndex] ?? null;\n    let resolvedDirection = direction.clone();\n    let resolvedLength = branchLength;\n    let resolvedThickness = structuralThickness;\n    let resolvedTaper = clamp01((branchDefinition?.taper ?? 50) / 100);\n\n    if (overrides) {\n      if (Number.isFinite(Number(overrides.length))) {\n        resolvedLength = THREE.MathUtils.lerp(0.45, 6, clamp01(Number(overrides.length) / 100));\n      }\n      if (Number.isFinite(Number(overrides.thickness))) {\n        resolvedThickness = THREE.MathUtils.lerp(0.02, 0.22, clamp01(Number(overrides.thickness) / 100));\n      }\n      if (Number.isFinite(Number(overrides.verticality))) {\n        const targetVerticality = lerp(-0.45, 0.65, clamp01(Number(overrides.verticality) / 100));\n        const horizontal = Math.sqrt(Math.max(0.02, 1 - targetVerticality * targetVerticality));\n        resolvedDirection.set(\n          Math.cos(azimuth) * horizontal,\n          targetVerticality,\n          Math.sin(azimuth) * horizontal,\n        ).normalize();\n      }\n      if (Number.isFinite(Number(overrides.taper))) {\n        resolvedTaper = clamp01(Number(overrides.taper) / 100);\n      }\n    }\n\n    const resolvedEnd = origin\n      .clone()\n      .add(resolvedDirection.clone().multiplyScalar(resolvedLength));\n\n    branches.push({\n      index: branchIndex,\n      trunkT,\n      origin,\n      end: resolvedEnd,\n      direction: resolvedDirection,\n      length: resolvedLength,\n      thickness: resolvedThickness,\n      localRadius,\n      azimuth,\n      elevation: Math.acos(THREE.MathUtils.clamp(resolvedDirection.y, -1, 1)),\n      taper: resolvedTaper,\n    });'''
if old not in s: raise SystemExit('branch push block not found')
s=s.replace(old,new)
old2='''    const tipThickness =\n      thickness * 0.24;'''
new2='''    const tipThickness =\n      thickness * THREE.MathUtils.lerp(0.46, 0.08, clamp01(Number(branch.taper ?? 50) / 100));'''
s=s.replace(old2,new2)
f.write_text(s)

# CrimsonTreeInteractionSystem replace branch logic and add refs/helpers
f=p/'src/components/world/CrimsonTreeInteractionSystem.jsx'
s=f.read_text()
s=s.replace('''  const editModeRef = useRef("trunk");\n  const dragRef = useRef(false);''','''  const editModeRef = useRef("trunk");\n  const branchScopeRef = useRef("global");\n  const branchGestureModeRef = useRef("length");\n  const activeBranchIndexRef = useRef(null);\n  const dragRef = useRef(false);''')
s=s.replace('''  const dragStartBendRef = useRef(50);\n  const definitionRef = useRef(null);''','''  const dragStartBendRef = useRef(50);\n  const dragStartBranchRef = useRef(null);\n  const dragStartPointRef = useRef(null);\n  const definitionRef = useRef(null);''')
# change mode handler
s=s.replace('''      editModeRef.current = mode;\n      window.dispatchEvent(new CustomEvent("crimson-tree-edit-mode-changed", { detail: { mode } }));''','''      editModeRef.current = mode;\n      dragRef.current = false;\n      window.dispatchEvent(new CustomEvent("crimson-tree-edit-mode-changed", { detail: { mode } }));''')
# insert branch controls handlers before trackDefinition
needle='''    const trackDefinition = (event) => {'''
insert='''    const setBranchScope = (event) => {\n      const scope = event.detail?.scope;\n      if (scope !== "global" && scope !== "single") return;\n      branchScopeRef.current = scope;\n      window.dispatchEvent(new CustomEvent("crimson-tree-branch-scope-changed", { detail: { scope } }));\n    };\n    const setBranchGestureMode = (event) => {\n      const mode = event.detail?.mode;\n      if (!["length", "verticality", "thickness", "frequency", "taper"].includes(mode)) return;\n      branchGestureModeRef.current = mode;\n      window.dispatchEvent(new CustomEvent("crimson-tree-branch-gesture-changed", { detail: { mode } }));\n    };\n    const trackDefinition = (event) => {'''
if needle not in s: raise SystemExit('track needle not found')
s=s.replace(needle,insert)
# replace onDown block start after target active determination through drag starts
old='''      if (!active) {\n        event.preventDefault();\n        event.stopPropagation();\n        event.stopImmediatePropagation?.();\n        enter(target.treeId);\n        return;\n      }\n      // Direct Tree Edit is a persistent mode. A click while already active\n      // begins an adjustment gesture; it must never toggle the mode off.\n      // ESC or the panel close action are the explicit exit points.\n      dragRef.current = true;\n      dragStartXRef.current = event.clientX;\n      dragStartYRef.current = event.clientY;\n      dragStartHeightRef.current = Number(definitionRef.current?.trunk?.height ?? 50);\n      dragStartBendRef.current = Number(definitionRef.current?.trunk?.bend ?? 50);\n      event.preventDefault();\n      event.stopPropagation();\n      event.stopImmediatePropagation?.();'''
new='''      if (!active) {\n        event.preventDefault();\n        event.stopPropagation();\n        event.stopImmediatePropagation?.();\n        enter(target.treeId);\n        return;\n      }\n      // Tree Edit is persistent. A click never toggles it off. In branch mode\n      // the clicked branch becomes the physical gesture handle.\n      dragRef.current = true;\n      dragStartXRef.current = event.clientX;\n      dragStartYRef.current = event.clientY;\n      dragStartHeightRef.current = Number(definitionRef.current?.trunk?.height ?? 50);\n      dragStartBendRef.current = Number(definitionRef.current?.trunk?.bend ?? 50);\n      dragStartPointRef.current = target.point?.clone?.() ?? null;\n      activeBranchIndexRef.current = Number.isFinite(Number(target.branch?.index)) ? Number(target.branch.index) : null;\n      dragStartBranchRef.current = {\n        length: Number(definitionRef.current?.branches?.length ?? 50),\n        verticality: Number(definitionRef.current?.branches?.verticality ?? 50),\n        thickness: Number(definitionRef.current?.branches?.thickness ?? 50),\n        frequency: Number(definitionRef.current?.branches?.frequency ?? 50),\n        taper: Number(definitionRef.current?.branches?.taper ?? 50),\n      };\n      event.preventDefault();\n      event.stopPropagation();\n      event.stopImmediatePropagation?.();'''
if old not in s: raise SystemExit('onDown block not found')
s=s.replace(old,new)
# replace branch onMove branch section
start='''      } else if (editModeRef.current === "branch") {'''
idx=s.find(start)
if idx<0: raise SystemExit('branch onMove start missing')
end=s.find('''      }\n    };\n    const onUp''', idx)
if end<0: raise SystemExit('branch onMove end missing')
oldsec=s[idx:end+7]
newsec='''      } else if (editModeRef.current === "branch") {\n        const start = dragStartBranchRef.current ?? {};\n        const gestureMode = event.shiftKey\n          ? "thickness"\n          : event.ctrlKey\n            ? "frequency"\n            : event.altKey\n              ? "taper"\n              : branchGestureModeRef.current;\n        const sensitivity = 0.32;\n        const deltaX = dx * sensitivity;\n        const deltaY = -dy * sensitivity;\n        const scope = branchScopeRef.current;\n\n        if (scope === "global" || activeBranchIndexRef.current == null) {\n          const patchValues = {};\n          if (gestureMode === "length") patchValues.length = THREE.MathUtils.clamp((start.length ?? 50) + deltaX, 0, 100);\n          if (gestureMode === "verticality") patchValues.verticality = THREE.MathUtils.clamp((start.verticality ?? 50) + deltaY, 0, 100);\n          if (gestureMode === "thickness") patchValues.thickness = THREE.MathUtils.clamp((start.thickness ?? 50) + deltaX, 0, 100);\n          if (gestureMode === "frequency") patchValues.frequency = THREE.MathUtils.clamp((start.frequency ?? 50) + deltaX, 0, 100);\n          if (gestureMode === "taper") patchValues.taper = THREE.MathUtils.clamp((start.taper ?? 50) + deltaX, 0, 100);\n          if (gestureMode === "length" && Math.abs(dy) > Math.abs(dx) * 1.35) {\n            patchValues.verticality = THREE.MathUtils.clamp((start.verticality ?? 50) + deltaY, 0, 100);\n          }\n          window.dispatchEvent(new CustomEvent("crimson-tree-edit-change", { detail: { treeId, patch: { branches: patchValues } } }));\n        } else {\n          const index = activeBranchIndexRef.current;\n          const existing = { ...(definitionRef.current?.branches?.overrides?.[index] ?? {}) };\n          const currentValue = Number(existing[gestureMode] ?? start[gestureMode] ?? 50);\n          const delta = gestureMode === "verticality" ? deltaY : deltaX;\n          existing[gestureMode] = THREE.MathUtils.clamp(currentValue + delta, 0, 100);\n          window.dispatchEvent(new CustomEvent("crimson-tree-edit-change", { detail: { treeId, patch: { branches: { overrides: { [index]: existing } } } } }));\n        }\n      }'''
s=s[:idx]+newsec+s[end+7:]
# Add keyboard shortcut branch mode commands and controller branch gestures. Replace onKey line.
s=s.replace('''    const onKey = (event) => { if (event.key === "Escape" && useInteractionStore.getState().activeTool === "TREE") { event.preventDefault(); exit(); } };''','''    const onKey = (event) => {\n      if (event.key === "Escape" && useInteractionStore.getState().activeTool === "TREE") { event.preventDefault(); exit(); return; }\n      if (useInteractionStore.getState().activeTool !== "TREE" || editModeRef.current !== "branch") return;\n      if (event.key.toLowerCase() === "g") { event.preventDefault(); setBranchScope({ detail: { scope: branchScopeRef.current === "global" ? "single" : "global" } }); }\n      if (event.key.toLowerCase() === "1") setBranchGestureMode({ detail: { mode: "length" } });\n      if (event.key.toLowerCase() === "2") setBranchGestureMode({ detail: { mode: "verticality" } });\n      if (event.key.toLowerCase() === "3") setBranchGestureMode({ detail: { mode: "thickness" } });\n      if (event.key.toLowerCase() === "4") setBranchGestureMode({ detail: { mode: "frequency" } });\n      if (event.key.toLowerCase() === "5") setBranchGestureMode({ detail: { mode: "taper" } });\n    };''')
# replace poll function
oldpoll_start='''    const poll = () => {\n      if (useInteractionStore.getState().activeTool !== "TREE" || !gamepadState.connected || editModeRef.current !== "trunk") return;'''
pollidx=s.find(oldpoll_start)
if pollidx<0: raise SystemExit('poll start missing')
pollend=s.find('''    const timer = window.setInterval(poll, 50);''', pollidx)
if pollend<0: raise SystemExit('poll end missing')
newpoll='''    const poll = () => {\n      if (useInteractionStore.getState().activeTool !== "TREE" || !gamepadState.connected) return;\n      const x = Number(gamepadState.leftStickX) || 0;\n      const y = Number(gamepadState.leftStickY) || 0;\n      if (Math.abs(x) < 0.12 && Math.abs(y) < 0.12) return;\n      const treeId = activeTreeIdRef.current;\n      if (!treeId) return;\n      if (editModeRef.current === "trunk") {\n        const height = THREE.MathUtils.clamp(Number(definitionRef.current?.trunk?.height ?? 50) - y * 1.4, 0, 100);\n        const bend = THREE.MathUtils.clamp(Number(definitionRef.current?.trunk?.bend ?? 50) + x * 1.4, 0, 100);\n        window.dispatchEvent(new CustomEvent("crimson-tree-edit-change", { detail: { treeId, patch: { trunk: { height, bend } } } }));\n        return;\n      }\n      if (editModeRef.current !== "branch") return;\n      const pad = navigator.getGamepads?.().find((entry) => entry?.connected);\n      const modifier = pad?.buttons?.[2]?.pressed ? "thickness" : pad?.buttons?.[3]?.pressed ? "frequency" : pad?.buttons?.[1]?.pressed ? "taper" : branchGestureModeRef.current;\n      const start = dragStartBranchRef.current ?? { ...definitionRef.current?.branches };\n      const gestureDelta = modifier === "verticality" ? -y * 1.4 : x * 1.4;\n      if (branchScopeRef.current === "global" || activeBranchIndexRef.current == null) {\n        const patchValues = {};\n        if (modifier === "length") patchValues.length = THREE.MathUtils.clamp(Number(definitionRef.current?.branches?.length ?? 50) + gestureDelta, 0, 100);\n        if (modifier === "verticality") patchValues.verticality = THREE.MathUtils.clamp(Number(definitionRef.current?.branches?.verticality ?? 50) + gestureDelta, 0, 100);\n        if (modifier === "thickness") patchValues.thickness = THREE.MathUtils.clamp(Number(definitionRef.current?.branches?.thickness ?? 50) + gestureDelta, 0, 100);\n        if (modifier === "frequency") patchValues.frequency = THREE.MathUtils.clamp(Number(definitionRef.current?.branches?.frequency ?? 50) + gestureDelta, 0, 100);\n        if (modifier === "taper") patchValues.taper = THREE.MathUtils.clamp(Number(definitionRef.current?.branches?.taper ?? 50) + gestureDelta, 0, 100);\n        window.dispatchEvent(new CustomEvent("crimson-tree-edit-change", { detail: { treeId, patch: { branches: patchValues } } }));\n      } else {\n        const index = activeBranchIndexRef.current;\n        const existing = { ...(definitionRef.current?.branches?.overrides?.[index] ?? {}) };\n        existing[modifier] = THREE.MathUtils.clamp(Number(existing[modifier] ?? start[modifier] ?? 50) + gestureDelta, 0, 100);\n        window.dispatchEvent(new CustomEvent("crimson-tree-edit-change", { detail: { treeId, patch: { branches: { overrides: { [index]: existing } } } } }));\n      }\n    };\n'''
s=s[:pollidx]+newpoll+s[pollend:]
# listeners
s=s.replace('''    window.addEventListener("crimson-tree-edit-change", trackDefinition);''','''    window.addEventListener("crimson-tree-edit-change", trackDefinition);\n    window.addEventListener("crimson-tree-branch-scope-request", setBranchScope);\n    window.addEventListener("crimson-tree-branch-gesture-request", setBranchGestureMode);''')
s=s.replace('''      window.removeEventListener("crimson-tree-edit-change", trackDefinition);''','''      window.removeEventListener("crimson-tree-edit-change", trackDefinition);\n      window.removeEventListener("crimson-tree-branch-scope-request", setBranchScope);\n      window.removeEventListener("crimson-tree-branch-gesture-request", setBranchGestureMode);''')
f.write_text(s)

# Panel: add branch scope/gesture UI and merge overrides
f=p/'src/components/ui/CrimsonTreeInteractionPanel.jsx'
s=f.read_text()
s=s.replace('''    branches: {\n      ...(definition?.branches ?? {}),\n      ...(patch?.branches ?? {}),\n      secondary: {''','''    branches: {\n      ...(definition?.branches ?? {}),\n      ...(patch?.branches ?? {}),\n      overrides: { ...(definition?.branches?.overrides ?? {}), ...(patch?.branches?.overrides ?? {}) },\n      secondary: {''')
s=s.replace('''  const [mode, setMode] = useState("trunk");''','''  const [mode, setMode] = useState("trunk");\n  const [branchScope, setBranchScope] = useState("global");\n  const [gestureMode, setGestureMode] = useState("length");''')
s=s.replace('''    function handleMode(event) {\n      setMode(event.detail?.mode ?? "trunk");\n    }''','''    function handleMode(event) {\n      setMode(event.detail?.mode ?? "trunk");\n    }\n\n    function handleBranchScope(event) {\n      setBranchScope(event.detail?.scope ?? "global");\n    }\n\n    function handleBranchGesture(event) {\n      setGestureMode(event.detail?.mode ?? "length");\n    }''')
s=s.replace('''    window.addEventListener("crimson-tree-edit-mode-changed", handleMode);''','''    window.addEventListener("crimson-tree-edit-mode-changed", handleMode);\n    window.addEventListener("crimson-tree-branch-scope-changed", handleBranchScope);\n    window.addEventListener("crimson-tree-branch-gesture-changed", handleBranchGesture);''')
s=s.replace('''      window.removeEventListener("crimson-tree-edit-mode-changed", handleMode);''','''      window.removeEventListener("crimson-tree-edit-mode-changed", handleMode);\n      window.removeEventListener("crimson-tree-branch-scope-changed", handleBranchScope);\n      window.removeEventListener("crimson-tree-branch-gesture-changed", handleBranchGesture);''')
needle='''      {mode === "branch" && (\n        <>\n          <div className="tg-tree-interaction-section">BRANCH CONTROL</div>'''
replacement='''      {mode === "branch" && (\n        <>\n          <div className="tg-tree-interaction-section">BRANCH CONTROL</div>\n          <div className="tg-tree-interaction-mode-row">\n            <button type="button" className={`tg-tree-interaction-mode ${branchScope === "global" ? "active" : ""}`} onClick={() => window.dispatchEvent(new CustomEvent("crimson-tree-branch-scope-request", { detail: { scope: "global" } }))}>ALL BRANCHES</button>\n            <button type="button" className={`tg-tree-interaction-mode ${branchScope === "single" ? "active" : ""}`} onClick={() => window.dispatchEvent(new CustomEvent("crimson-tree-branch-scope-request", { detail: { scope: "single" } }))}>SINGLE BRANCH</button>\n          </div>\n          <div className="tg-tree-interaction-section">GESTURE</div>\n          <div className="tg-tree-interaction-mode-row">\n            {[["length","LENGTH"],["verticality","VERTICALITY"],["thickness","THICKNESS"],["frequency","FREQUENCY"],["taper","TAPER"]].map(([key,label]) => (\n              <button key={key} type="button" className={`tg-tree-interaction-mode ${gestureMode === key ? "active" : ""}`} onClick={() => window.dispatchEvent(new CustomEvent("crimson-tree-branch-gesture-request", { detail: { mode: key } }))}>{label}</button>\n            ))}\n          </div>'''
if needle not in s: raise SystemExit('panel branch needle missing')
s=s.replace(needle,replacement)
s=s.replace('''          <div className="tg-tree-interaction-hint">LOOK AT TRUNK / CLICK TO ANCHOR / DRAG TO EXTRUDE / CLICK TO COMMIT</div>''','''          <div className="tg-tree-interaction-hint">DRAG = GESTURE · SHIFT = THICKNESS · CTRL = FREQUENCY · ALT = TAPER · G = SINGLE/ALL</div>''')
f.write_text(s)

# CrimsonTreeModel: ensure vertices changes regenerate geometry and pass taper through data already done
f=p/'src/components/world/CrimsonTreeModel.jsx'
s=f.read_text()
s=s.replace('''    generatorLeaves?.gradientColor,\n    generatorLeaves?.color,\n    crownColor,''','''    generatorLeaves?.gradientColor,\n    generatorLeaves?.color,\n    generatorLeaves?.vertices,\n    crownColor,''')
f.write_text(s)

# Shortcuts: harden key/gamepad listeners and expose keyboard shortcut dispatch even if focus is in a panel.
f=p/'src/components/ui/GamepadMenuNavigator.jsx'
s=f.read_text()
s=s.replace('''      if (event.code === "KeyV" && !event.repeat) {\n        event.preventDefault();\n        toggleShortcutPanel();\n        return;\n      }''','''      if (event.code === "KeyV" && !event.repeat) {\n        event.preventDefault();\n        event.stopPropagation();\n        toggleShortcutPanel();\n        return;\n      }''')
s=s.replace('''    window.addEventListener("keydown", onKeyDown);\n    return () => window.removeEventListener("keydown", onKeyDown);''','''    window.addEventListener("keydown", onKeyDown, true);\n    document.addEventListener("keydown", onKeyDown, true);\n    return () => {\n      window.removeEventListener("keydown", onKeyDown, true);\n      document.removeEventListener("keydown", onKeyDown, true);\n    };''')
# avoid double event from window+document by mark
s=s.replace('''    function onKeyDown(event) {\n      if (event.target?.closest?.("input, textarea, select")) return;''','''    function onKeyDown(event) {\n      if (event.__tgShortcutHandled) return;\n      if (event.target?.closest?.("input, textarea, select")) return;''')
s=s.replace('''        event.stopPropagation();\n        toggleShortcutPanel();''','''        event.stopPropagation();\n        event.__tgShortcutHandled = true;\n        toggleShortcutPanel();''')
f.write_text(s)

# version + patch notes
pkg=p/'package.json'; import json
j=json.loads(pkg.read_text()); j['version']='1.6.03.03'; pkg.write_text(json.dumps(j,indent=2)+'\n')
notes=p/'PATCH_NOTES_1.6.03.03.md'
notes.write_text('''# Testing Grounds 1.6.03.03\n\n## Focus\nCrimson Tree gesture-first branch editing, global branch response by default, single-branch precision mode, leaf vertex regeneration, and shortcut input hardening.\n\n## Tree branch interaction\n- Branch edit defaults to ALL BRANCHES.\n- Clicking a branch supplies the physical gesture handle; the operation is applied to the procedural branch population.\n- Default gesture: horizontal drag controls LENGTH; strong vertical drag controls VERTICALITY.\n- Gesture modes: LENGTH, VERTICALITY, THICKNESS, FREQUENCY, TAPER.\n- Keyboard modifiers: Shift=THICKNESS, Ctrl=FREQUENCY, Alt=TAPER.\n- G toggles ALL BRANCHES / SINGLE BRANCH.\n- Number keys 1-5 select gesture modes.\n- Xbox: Left Stick is the gesture; X modifier=THICKNESS, Y modifier=FREQUENCY, B modifier=TAPER.\n- Single branch overrides are stored by procedural branch index.\n- Branch geometry now respects per-branch taper overrides.\n\n## Leaf editing\n- Leaf vertex edits now invalidate/rebuild canopy geometry when canonical vertices change.\n\n## Shortcuts\n- V listener hardened to capture phase.\n- D-pad shortcut context retained: closed panel = menu navigation; held D-pad Up = shortcut context.\n\n## Protected\n- Terrain and object systems from 1.6.03.02 are unchanged.\n- Sun controls unchanged.\n''')
print('patched')
