export const NATURE_PACK_OBJECTS = Object.freeze([
  { id: "nature-bush_common", name: "BUSH COMMON", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Bush_Common.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-bush_common_flowers", name: "BUSH COMMON FLOWERS", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Bush_Common_Flowers.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-clover_1", name: "CLOVER 1", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Clover_1.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-clover_2", name: "CLOVER 2", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Clover_2.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-commontree_1", name: "COMMONTREE 1", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/CommonTree_1.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-commontree_2", name: "COMMONTREE 2", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/CommonTree_2.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-commontree_3", name: "COMMONTREE 3", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/CommonTree_3.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-commontree_4", name: "COMMONTREE 4", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/CommonTree_4.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-commontree_5", name: "COMMONTREE 5", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/CommonTree_5.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-deadtree_1", name: "DEADTREE 1", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/DeadTree_1.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-deadtree_2", name: "DEADTREE 2", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/DeadTree_2.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-deadtree_3", name: "DEADTREE 3", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/DeadTree_3.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-deadtree_4", name: "DEADTREE 4", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/DeadTree_4.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-deadtree_5", name: "DEADTREE 5", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/DeadTree_5.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-fern_1", name: "FERN 1", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Fern_1.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-flower_3_group", name: "FLOWER 3 GROUP", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Flower_3_Group.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-flower_3_single", name: "FLOWER 3 SINGLE", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Flower_3_Single.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-flower_4_group", name: "FLOWER 4 GROUP", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Flower_4_Group.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-flower_4_single", name: "FLOWER 4 SINGLE", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Flower_4_Single.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-grass_common_short", name: "GRASS COMMON SHORT", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Grass_Common_Short.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-grass_common_tall", name: "GRASS COMMON TALL", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Grass_Common_Tall.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-grass_wispy_short", name: "GRASS WISPY SHORT", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Grass_Wispy_Short.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-grass_wispy_tall", name: "GRASS WISPY TALL", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Grass_Wispy_Tall.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-mushroom_common", name: "MUSHROOM COMMON", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Mushroom_Common.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-mushroom_laetiporus", name: "MUSHROOM LAETIPORUS", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Mushroom_Laetiporus.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-pebble_round_1", name: "PEBBLE ROUND 1", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/Pebble_Round_1.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-pebble_round_2", name: "PEBBLE ROUND 2", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/Pebble_Round_2.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-pebble_round_3", name: "PEBBLE ROUND 3", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/Pebble_Round_3.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-pebble_round_4", name: "PEBBLE ROUND 4", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/Pebble_Round_4.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-pebble_round_5", name: "PEBBLE ROUND 5", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/Pebble_Round_5.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-pebble_square_1", name: "PEBBLE SQUARE 1", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/Pebble_Square_1.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-pebble_square_2", name: "PEBBLE SQUARE 2", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/Pebble_Square_2.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-pebble_square_3", name: "PEBBLE SQUARE 3", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/Pebble_Square_3.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-pebble_square_4", name: "PEBBLE SQUARE 4", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/Pebble_Square_4.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-pebble_square_5", name: "PEBBLE SQUARE 5", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/Pebble_Square_5.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-pebble_square_6", name: "PEBBLE SQUARE 6", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/Pebble_Square_6.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-petal_1", name: "PETAL 1", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Petal_1.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-petal_2", name: "PETAL 2", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Petal_2.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-petal_3", name: "PETAL 3", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Petal_3.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-petal_4", name: "PETAL 4", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Petal_4.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-petal_5", name: "PETAL 5", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Petal_5.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-pine_1", name: "PINE 1", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/Pine_1.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-pine_2", name: "PINE 2", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/Pine_2.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-pine_3", name: "PINE 3", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/Pine_3.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-pine_4", name: "PINE 4", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/Pine_4.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-pine_5", name: "PINE 5", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/Pine_5.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-plant_1", name: "PLANT 1", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Plant_1.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-plant_1_big", name: "PLANT 1 BIG", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Plant_1_Big.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-plant_7", name: "PLANT 7", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Plant_7.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-plant_7_big", name: "PLANT 7 BIG", kind: "foliage", source: "quaternius", modelPath: "/assets/quaternius-nature/Plant_7_Big.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-rockpath_round_small_1", name: "ROCKPATH ROUND SMALL 1", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/RockPath_Round_Small_1.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-rockpath_round_small_2", name: "ROCKPATH ROUND SMALL 2", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/RockPath_Round_Small_2.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-rockpath_round_small_3", name: "ROCKPATH ROUND SMALL 3", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/RockPath_Round_Small_3.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-rockpath_round_thin", name: "ROCKPATH ROUND THIN", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/RockPath_Round_Thin.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-rockpath_round_wide", name: "ROCKPATH ROUND WIDE", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/RockPath_Round_Wide.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-rockpath_square_small_1", name: "ROCKPATH SQUARE SMALL 1", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/RockPath_Square_Small_1.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-rockpath_square_small_2", name: "ROCKPATH SQUARE SMALL 2", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/RockPath_Square_Small_2.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-rockpath_square_small_3", name: "ROCKPATH SQUARE SMALL 3", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/RockPath_Square_Small_3.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-rockpath_square_thin", name: "ROCKPATH SQUARE THIN", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/RockPath_Square_Thin.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-rockpath_square_wide", name: "ROCKPATH SQUARE WIDE", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/RockPath_Square_Wide.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-rock_medium_1", name: "ROCK MEDIUM 1", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/Rock_Medium_1.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-rock_medium_2", name: "ROCK MEDIUM 2", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/Rock_Medium_2.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-rock_medium_3", name: "ROCK MEDIUM 3", kind: "rock", source: "quaternius", modelPath: "/assets/quaternius-nature/Rock_Medium_3.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-twistedtree_1", name: "TWISTEDTREE 1", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/TwistedTree_1.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-twistedtree_2", name: "TWISTEDTREE 2", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/TwistedTree_2.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-twistedtree_3", name: "TWISTEDTREE 3", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/TwistedTree_3.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-twistedtree_4", name: "TWISTEDTREE 4", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/TwistedTree_4.gltf", pack: "Quaternius Stylized Nature Pack" },
  { id: "nature-twistedtree_5", name: "TWISTEDTREE 5", kind: "tree", source: "quaternius", modelPath: "/assets/quaternius-nature/TwistedTree_5.gltf", pack: "Quaternius Stylized Nature Pack" },
]);
